name: Comment on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    name: An example job to comment a PR
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Post a comment on the PR
      - name: Add a comment to the PR
        uses: actions/github-script@v6
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const comment = `
            Thank you for your contribution! 🎉

            Here's a table for your reference:

            | Env | URL |
            |----------|----------|
            | Staging    | ${branchName}.staging.com   |
            | Smoke    | ${branchName}.prod.com   |
            `;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment,
            });
