name: Comment on Pull Request

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Post a comment on the PR
      - name: Add a comment to the PR
        uses: actions/github-script@v6
        with:
          script: |
            const comment = "Thank you for opening this pull request! 🎉\n\nWe will review it soon.";
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment,
            });
